version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    container_name: workshop-elasticsearch
    environment:
      - "discovery.type=single-node"
      - node.name=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9200"
      - "9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.9
    container_name: workshop-kibana
    ports:
      - "5601:5601"